import { Vaccine} from './vaccine';

// export const VACCINS: Vaccine[] = [
//     {id: 0,name: 'name', description: 'improves ', bodyPart: 'Eyes', CompanyName: 'Pfizer-BioNTech'},
//     {id: 1,name: 'name', description: 'description', bodyPart: 'Nose', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 2,name: 'name', description: 'description', bodyPart: 'Mouth', CompanyName: 'Johnson & Johnson'},
//     {id: 3,name: 'name', description: 'description', bodyPart: 'Ears', CompanyName: 'AstraZeneca'},
//     {id: 4,name: 'name', description: 'description', bodyPart: 'Left Arm', CompanyName: 'Moderna'},
//     {id: 5,name: 'name', description: 'description', bodyPart: 'Right Arm', CompanyName: 'Sputnik'},
//     {id: 6,name: 'name', description: 'description', bodyPart: 'Torso', CompanyName: 'Pfizer-BioNTech'},
//     {id: 7,name: 'name', description: 'description', bodyPart: 'Legs', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 8,name: 'name', description: 'description', bodyPart: 'Eyes', CompanyName: 'Johnson & Johnson'},
//     {id: 9,name: 'name', description: 'description', bodyPart: 'Nose', CompanyName: 'AstraZeneca'},
//     {id: 10,name: 'name', description: 'description', bodyPart: 'Mouth', CompanyName: 'Moderna'},
//     {id: 11,name: 'name', description: 'description', bodyPart: 'Ears', CompanyName: 'Sputnik'},
//     {id: 12,name: 'name', description: 'description', bodyPart: 'Left Arm', CompanyName: 'Pfizer-BioNTech'},
//     {id: 13,name: 'name', description: 'description', bodyPart: 'Right Arm', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 14,name: 'name', description: 'description', bodyPart: 'Torso', CompanyName: 'Johnson & Johnson'},
//     {id: 15,name: 'name', description: 'description', bodyPart: 'Legs', CompanyName: 'AstraZeneca'},
//     {id: 16,name: 'name', description: 'description', bodyPart: 'Eyes', CompanyName: 'Moderna'},
//     {id: 17,name: 'name', description: 'description', bodyPart: 'Nose', CompanyName: 'Sputnik'},
//     {id: 18,name: 'name', description: 'description', bodyPart: 'Mouth', CompanyName: 'Pfizer-BioNTech'},
//     {id: 19,name: 'name', description: 'description', bodyPart: 'Ears', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 20,name: 'name', description: 'description', bodyPart: 'Left Arm', CompanyName: 'Johnson & Johnson'},
//     {id: 21,name: 'name', description: 'description', bodyPart: 'Right Arm', CompanyName: 'AstraZeneca'},
//     {id: 22,name: 'name', description: 'description', bodyPart: 'Torso', CompanyName: 'Moderna'},
//     {id: 23,name: 'name', description: 'description', bodyPart: 'Legs', CompanyName: 'Sputnik'},
//     {id: 24,name: 'name', description: 'description', bodyPart: 'Eyes', CompanyName: 'Pfizer-BioNTech'},
//     {id: 25,name: 'name', description: 'description', bodyPart: 'Nose', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 26,name: 'name', description: 'description', bodyPart: 'Mouth', CompanyName: 'Johnson & Johnson'},
//     {id: 27,name: 'name', description: 'description', bodyPart: 'Ears', CompanyName: 'AstraZeneca'},
//     {id: 28,name: 'name', description: 'description', bodyPart: 'Left Arm', CompanyName: 'Moderna'},
//     {id: 29,name: 'name', description: 'description', bodyPart: 'Right Arm', CompanyName: 'Sputnik'},
//     {id: 30,name: 'name', description: 'description', bodyPart: 'Torso', CompanyName: 'Pfizer-BioNTech'},
//     {id: 31,name: 'name', description: 'description', bodyPart: 'Legs', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 32,name: 'name', description: 'description', bodyPart: 'Eyes', CompanyName: 'Johnson & Johnson'},
//     {id: 33,name: 'name', description: 'description', bodyPart: 'Nose', CompanyName: 'AstraZeneca'},
//     {id: 34,name: 'name', description: 'description', bodyPart: 'Mouth', CompanyName: 'Moderna'},
//     {id: 35,name: 'name', description: 'description', bodyPart: 'Ears', CompanyName: 'Sputnik'},
//     {id: 36,name: 'name', description: 'description', bodyPart: 'Left Arm', CompanyName: 'Pfizer-BioNTech'},
//     {id: 37,name: 'name', description: 'description', bodyPart: 'Right Arm', CompanyName: 'Sputnik'},
//     {id: 38,name: 'name', description: 'description', bodyPart: 'Torso', CompanyName: 'Janssen Pharmaceutica'},
//     {id: 39,name: 'name', description: 'description', bodyPart: 'Legs', CompanyName: 'Johnson & Johnson'},
// ]